lib/vanity/experiment/ab_test.rb
Ruby 2.2 introduced a change into how default arguments are parsed[1].
Now when you wish to use a method as a default argument you need to be
explicit by using parenthasis.
For example
`def bar(foo=foo)`
will need to be re-written
`def bar(foo=foo())`
This commit introduces a fix for this issue.
*Note* I initially looked into updating the specs (to use ruby 2.2.0),
however I ran into a number of issues with the appraisal test suite and
older versions of rails.
[1]https://bugs.ruby-lang.org/issues/10314
=> Introduce Ruby 2.2 support.

lib/vanity/playground.rb, test/playground_test.rb
This also removed the deprecated Playground#define method as it contributes to the confusion.
This should close #232. Note that the only line that _needed_ to be removed was https://github.com/assaf/vanity/pull/234/files#diff-878670dc9fdffe69dd016dbfedd02ad2L235.
=> Save experiments only once on load

README.rdoc
RSpec does not work with out the test environment having a defined adapter.  Also if using Ruby 2.2 you may need to use the beta
=> Working with Ruby 2.20 and getting RSpec running, work arounds

lib/vanity/autoconnect.rb
This is deprecated as of Rails 4.1, but may still be used (especially by rails 3 projects).
=> Include `db:test:load` in list of blacklisted autoconnect rake tasks.

CHANGELOG, Gemfile.lock, gemfiles/rails3.gemfile.lock, gemfiles/rails31.gemfile.lock, gemfiles/rails32.gemfile.lock, gemfiles/rails4.gemfile.lock, lib/vanity/experiment/ab_test.rb, lib/vanity/version.rb
Cherry-picks 1b5bf18636caa5eae279e2aef2e24c923e63b141.
Closes https://github.com/assaf/vanity/issues/273.
=> Backport fix for circular argument reference in 2.2.0

lib/vanity/configuration.rb
It will exclude any User-Agent with the string 'bot', 'crawler', or
'spider'.
=> Update default_request_filter to exclude more bots

doc/configuring.textile, lib/vanity/configuration.rb, lib/vanity/frameworks/rails.rb, test/frameworks/rails/action_controller_test.rb
* Changed `vanity_id` cookie to a permanent cookie.
* Added ability to change the name, domain, path, secure, and httponly property of the cookie in the Vanity.configuration.
=> Specify cookie options in configuration.

lib/vanity/experiment/ab_test.rb, test/experiment/ab_test.rb
Allows you to define probabilities for test alternatives using a simple hash format:
```ruby
ab_test "Foo" do
alternatives :a => 30, :b => 70
end
```
=> Define test alternatives with custom probabilities

README.md, doc/configuring.textile, doc/identity.textile, lib/generators/templates/vanity_migration.rb, lib/vanity/adapters/abstract_adapter.rb, lib/vanity/adapters/active_record_adapter.rb, lib/vanity/adapters/mock_adapter.rb, lib/vanity/adapters/mongodb_adapter.rb, lib/vanity/adapters/redis_adapter.rb, lib/vanity/configuration.rb, lib/vanity/experiment/ab_test.rb, lib/vanity/experiment/alternative.rb, lib/vanity/frameworks/rails.rb, lib/vanity/locales/vanity.en.yml, lib/vanity/locales/vanity.pt-BR.yml, lib/vanity/templates/_ab_test.erb, lib/vanity/templates/_experiment.erb, lib/vanity/templates/vanity.css, lib/vanity/templates/vanity.js, test/commands/report_test.rb, test/experiment/ab_test.rb, test/experiment/base_test.rb, test/frameworks/rails/action_controller_test.rb, test/frameworks/rails/action_mailer_test.rb, test/frameworks/rails/action_view_test.rb, test/helper_test.rb, test/playground_test.rb, test/test_helper.rb, test/web/rails/dashboard_test.rb
Merged some of the [changes developed by ApartmentList](http://blog.apartmentlist.com/vanity-ab-testing/). ([github](https://github.com/apartmentlist/vanity)).
* Experiments start off in the disabled state, and only become enabled after a dashboard interaction.
* Enable & disable experiments with the push of a button.  When disabled, the `default` choice is used.
* Control when and how experiments should complete by clicking a 'complete' button on the dashboard.
* Changed active record `increment!` to `update_counters` which performs an atomic SQL update.
=> Merge some ApartmentList changes into Vanity 2.0.0

lib/vanity/frameworks/rails.rb
To allow for including add_participant into a controller without the rest of the vanity dashboard.
However, if you include Vanity::Rails::Dashboard, the add_participant action is still included.
=> Separate add_participant into separate module.

doc/metrics.textile, lib/vanity/metric/active_record.rb, test/metric/active_record_test.rb
This allows objects created on the backend (outside the ActionController) context to still have an associated identity.
Additionally, fixes a bug with the `after_create` callback so that the current `Vanity.context.vanity_identity` is passed along to properly record the conversion for the participant.
=> ActiveRecord model metrics can provide their own identity source

lib/vanity/experiment/ab_test.rb, lib/vanity/experiment/base.rb, lib/vanity/frameworks/rails.rb, test/experiment/ab_test.rb
This block is called on each `choose`.  If it returns `true` then the default is returned.
The block is called with the current `request` or `nil` if there is none.
=> Add `reject` method to experiment definition.

lib/vanity/experiment/ab_test.rb
MD5.hexdigest provides a flat (but noisy) distribution of hex digits, but the typo converting them back to integers with base 17 adds a very slight bias to the results, increasing the size of some low-order buckets. eg this calculation using a range instead of MD5 to provide the evenly distributed input: (0..9999999).each_with_object(Hash.new(0)) {|d, h| h[d.to_s(16).to_i(17) % 100 < 5] += 1 } => {true=>500025, false=>9499975} . It's only a slight loading of the dice, and would be very hard to spot in real experiments because it's lost in the noise of the MD5 distribution. Spotted via code review not tests.
=> Fix 'base 17' typo, correct id bucketing

ab_testing.html, index.html
So after digging through this code for a few days, I realized that the "exploitation" and "exploration" mentioned in the docs won't actually be done unless you specify a `rebalance_frequency`. Seemed like that should be mentioned.
Additionally, the API Reference link is currently broken. This was (apparently) fixed in an earlier commit but docs were never updated.
=> Update API reference link & notes about `rebalance_frequency`

lib/vanity/frameworks/rails.rb
Changes Mime::HTML to Mime[:html] to avoid a dep warning. Fixes #312.
=> Resolve Rails 5 deprecation warning for Mime::HTML

.gitignore, lib/vanity/adapters/mock_adapter.rb, test/adapters/mock_adapter_test.rb
Hi there,
While switching to the mock adapter for test usage, we noticed that the `#ab_seen` and `#ab_assigned` methods from the abstract adapter weren't implemented in the mock adapter.
This PR introduces test coverage for the mock adapter, and adds implementations for the missing methods. I'd really appreciate a look-over to make sure I've got the meaning of these methods correct.
At the moment I've only added tests for the metric- and experiment-related methods, not the connection management ones. This because I think the former can probably be extracted and used to test all the adapters, whereas tests for the connection management behaviour are more likely to be adapter-specific. If you're happy to merge this, I'll have a stab at sharing the tests with the redis, mongo etc. adapters. …
=> Implement #ab_seen and #ab_assigned in MockAdapter

lib/vanity/adapters/abstract_adapter.rb, lib/vanity/adapters/active_record_adapter.rb, lib/vanity/adapters/mock_adapter.rb, lib/vanity/adapters/mongodb_adapter.rb, lib/vanity/adapters/redis_adapter.rb, lib/vanity/experiment/ab_test.rb, test/adapters/shared_tests.rb, test/vanity_test.rb
As noted in #309, the `#ab_seen` adapter method currently takes an instance of `Alternative`, where all other adapter methods take an alternative id.
Since this has the potential to cause confusion, I thought it might be best to support both calling styles, logging a deprecation notice if the method is called with an `Alternative` instance, but still returning the correct response. We can then remove support for the old method signature after a respectful period of silence. :-)
(I've also silenced the deprecation warnings emitted by another test, hope that's okay.)
=> Deprecate calling #ab_seen with alternative instance

lib/vanity/adapters/active_record_adapter.rb
This replaces `delete_all(conditions)` with `where(conditions).delete_all`. 
This is necessary for Rails 5.1 as `delete_all` [no longer receives conditions](https://github.com/rails/rails/pull/27503/commits/e7381d289e4f8751dcec9553dcb4d32153bd922b).
=> Do not use delete_all's deprecated parameters (Rails 5.1 compatibility)

lib/vanity/frameworks/rails.rb
This change renames the before_filter and after_filter calls to be Rails 5 compatible. It is based on the feedback in PR #315.
I've been running this patch in production and it's working well.
Sorry to open a duplicative PR, but I didn't hear back from @terracatta when I opened a PR against their PR: https://github.com/terracatta/vanity/pull/1
Thank you for this awesome gem.
=> Use send to change _filter/_action callbacks for Rails 5

lib/vanity/frameworks/rails.rb
In Rails 5 the `render` method deprecated a number of options including
the `nothing` option [1] (this option was removed entirely in Rails
5.1).
Previously vanity relied on this method for implementing its
`add_participant` controller endpoint.
Rather than using `render nothing: true`, we can use the `head` method
if we do not require a body in the response.
**Notes**
It looks like the `head` method is available in all versions of Rails
supported by Vanity (including Rails 3.2).
[1] https://github.com/rails/rails/pull/20336
=> Fix `add_participant` on Rails 5.1

lib/generators/templates/add_unique_indexes_migration.rb, lib/generators/templates/vanity_migration.rb, lib/generators/vanity/add_unique_indexes_generator.rb, lib/vanity/adapters/active_record_adapter.rb
I've noticed that there's a race condition using the activerecord adapater when vanity creates experiments or rows in the conversions table - ever now and a again we end up with duplicate rows in those tables.
This can be fixed by adding unique indexes to those tables and with the code change in this PR. The default vanity migrations should also be changed for this to be effective, but I'm not sure how that is usually managed (for example, how do existing users update their vanity tables?)
=> Race condition when creating experiments using AR adapter

lib/generators/templates/add_participants_unique_index_migration.rb, lib/generators/templates/add_unique_indexes_migration.rb, lib/generators/templates/vanity_migration.rb, lib/generators/vanity/add_participants_unique_index_generator.rb, lib/vanity/adapters/active_record_adapter.rb
There's a race condition that can lead to duplicate participation -- and possibly conflicting segmentation -- for a given experiment.
Thread A:   `Vanity.ab_test(:my_experiment)`
Thread B:   `Vanity.ab_test(:my_experiment)`
---
To prevent this situation:
1) Make the existing (experiment_id, identity) index a unique index.
2) Update the Vanity::Participant code to gracefully handle the dup record failure.
=> Prevent dupe participation in same experiment

lib/vanity/templates/vanity.css
=> Fix broken table size in report dashboard

Gemfile.lock, vanity.gemspec
Fix the bundle install error as yajl-ruby 1.2.1 not compatible with ruby 2.4
```
current directory: /Users/jiazhen/Documents/vanity/.bundle/gems/yajl-ruby-1.2.1/ext/yajl
make "DESTDIR="
compiling yajl.c
compiling yajl_alloc.c
compiling yajl_buf.c
compiling yajl_encode.c
compiling yajl_ext.c
yajl_ext.c:881:22: error: use of undeclared identifier 'rb_cFixnum'
rb_define_method(rb_cFixnum, "to_json", rb_yajl_json_ext_fixnum_to_json, -1);
```
=> Upgrade yajl-ruby so that it can be compiled with ruby 2.4

Gemfile.lock, lib/vanity/adapters/redis_adapter.rb, test/adapters/shared_tests.rb
Currently the redis adapter's `#destroy_experiment` method only removes experiment metadata; all participant data is retained even if the experiment is reset. This can lead to large numbers of old keys hanging around in redis instances, requiring manual cleanup.
This change uses redis's SCAN command[1] to delete all keys matching the experiment prefix, which should completely reset the experiment.
The SCAN command works in batches, each time returning a cursor value that can be used in subsequent calls; when the cursor "0" is returned, the scan is complete.
I've tried to test this here by making the shared adapter test more complete; I haven't got this running locally at the moment, however, so it's likely to be failing on travis and I'll patch it up with subsequent commits.
Is this …
=> Fully destroy experiments using the Redis adapter

lib/vanity/locales/vanity.ru.yml
When loading the Vanity dashboard with an English locale, all the
interface text was being shown in Russian.
We _think_ this is because the Russian locale file uses the `en:` key,
and as it loads after the English locale it is overwriting the English
values.
We've updated the Russian locale to use the `ru:` key.
=> Fix Russian locale file key

lib/vanity/experiment/ab_test.rb
Prior to this fix, stubbing a specific outcome with AbTest#chooses
would occasionally set the 'shown' bit on a participant
because the code at
https://github.com/assaf/vanity/blob/469917acf/lib/vanity/experiment/ab_test.rb#L242
noticed that the persisted participant's alternative differed
from the alternative selected by the hashing algorithm in #alternative_for
This would cause problems downstream in the conversion code
because #ab_showing returns true on this participant.
=> Fix AbTest#alternative_for to always prefer persisted participants

lib/vanity/configuration.rb, test/dummy/config/initializers/vanity.rb, test/dummy/config/vanity.yml
@bensheldon 
Rubocop changed `YAML.load` -> `YAML.safe_load` and safe_load doesn't support aliases in yml by default. This PR fixes that
=> Enable aliases for config

lib/vanity/adapters/redis_adapter.rb, test/adapters/redis_adapter_test.rb
Hello!
First of all thanks for this amazing library!
I'm trying to upgrade redis from 4.4 to 4.6 in my project. It's rather painless but I noticed Vanity wasn't working properly as it assumes `exists` to return true or false which in recent redis-rb versions was changed and now it returns number of matching keys unless `Redis.exists_returns_integer` is set to false. But that option is deprecated and will be removed in redis-rb 5.0. 
So for boolean checks it is recommended to use `exists?` method and right now it's a bit messy with all that possibilities out there. So I tried not to break anything by checking for `exists?` method which we now for sure gives us boolean result. And if that method is absent, we're probing `exists` and if it's numeric we are calculating `> 0` if not we're …
=> Use Redis#exists? and fallback to #exists which could be either boolean or integer in recent redis gem versions
